// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5DE34CSwpicXh55DcyQ4XrWYLspeVYfE',
    appId: '1:513708130394:web:3b14a5f0b49aadf4c21863',
    messagingSenderId: '513708130394',
    projectId: 'pasarmaya-itb',
    authDomain: 'pasarmaya-itb.firebaseapp.com',
    storageBucket: 'pasarmaya-itb.appspot.com',
    measurementId: 'G-N5RGCZ7BCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtXb_INf9isHuo7OHq1Pok5DveeRtYYnA',
    appId: '1:513708130394:android:a371d090f9a21ff9c21863',
    messagingSenderId: '513708130394',
    projectId: 'pasarmaya-itb',
    storageBucket: 'pasarmaya-itb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7ZBJpZ-HEMp4KI_P8gA4q0l05jt-eq8',
    appId: '1:513708130394:ios:bf16be7e0dfa341fc21863',
    messagingSenderId: '513708130394',
    projectId: 'pasarmaya-itb',
    storageBucket: 'pasarmaya-itb.appspot.com',
    iosBundleId: 'com.example.pasya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_7ZBJpZ-HEMp4KI_P8gA4q0l05jt-eq8',
    appId: '1:513708130394:ios:bf16be7e0dfa341fc21863',
    messagingSenderId: '513708130394',
    projectId: 'pasarmaya-itb',
    storageBucket: 'pasarmaya-itb.appspot.com',
    iosBundleId: 'com.example.pasya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5DE34CSwpicXh55DcyQ4XrWYLspeVYfE',
    appId: '1:513708130394:web:5b8a80969c2a175ac21863',
    messagingSenderId: '513708130394',
    projectId: 'pasarmaya-itb',
    authDomain: 'pasarmaya-itb.firebaseapp.com',
    storageBucket: 'pasarmaya-itb.appspot.com',
    measurementId: 'G-LTR7F1RW1T',
  );

}